# Change these first
owner: omawhite # Your GitHub organization or username, where this repository lives
repo: portfolio-uptime-monitor # The name of this repository

sites:
  - name: louiswhite.me
    url: https://louiswhite.me
  - name: www.louiswhite.me
    url: https://www.louiswhite.me
  - name: netlify url
    url: https://omars-next-portfolio.netlify.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /portfolio-uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: 'Uptime monitoring for louiswhite.me'
  introMessage: This is a sample status page for my portfolio site which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
